{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: waas-prometheus-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
data:
  prometheus.yml: |-
{{ .Files.Get "files/prometheus.yml" | replace "SCRAPE_INTERVAL" .Values.scrape.interval | replace "TIMEOUT_INTERVAL" .Values.scrape.timeout | indent 4 }}
{{- if .Values.gatherK8sPerformanceMetrics }}
{{ .Files.Get "files/prometheus.performance.yml" | indent 4 }}
{{- end }}
{{- end }}
