{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: waas-prometheus-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
spec:
  selector:
    configid: waas-prometheus-container
  type: {{ .Values.serviceType }}
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
      {{- if (eq "NodePort" .Values.serviceType) }}
      nodePort: {{ .Values.promNodePort }}
      {{- end }}
    - name: http-push
      port: 9091
      protocol: TCP
      targetPort: 9091
      {{- if (eq "NodePort" .Values.serviceType) }}
      nodePort: {{ .Values.pushNodePort }}
      {{- end }}
{{- end -}}
