{{- if and .Values.perfNginx (eq .Values.configType "mapping") }}
apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  perf-sample
  labels:
    release: waas
  namespace: {{ .Release.Namespace }}
spec:
  policies:
  - name: all-policy
    operatorEmail: support@radware.com
    protections:
    - id: perf
      signatures:
        opMode: Active
      expressions:
        opMode: Active
    classifiers:
    - protectionId: perf
      hostname: '*'
      id: perf-sample
      path:
        operand: Prefix
        value: /
{{- end }}