{{- if and .Values.vampi (eq .Values.configType "mapping") }}
apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  vampi-sample
  labels:
    release: waas
  namespace: {{ .Release.Namespace }}
spec:
  policies:
  - name: vampi-policy
    operatorEmail: support@radware.com
    protections:
    - id: vampi
      signatures:
        opMode: Active
      expressions:
        opMode: Active
    classifiers:
    - protectionId: vampi
      hostname: '*'
      id: vampi-sample
      path:
        operand: Prefix
        value: /
{{- end }}