{{- if and .Values.httpbin (eq .Values.configType "mapping") }}
apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  labels:
    release: waas
  namespace: {{ .Release.Namespace }}
spec:
  policies:
  - name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    - id: httpbin
      signatures:
        opMode: Active
      expressions:
        opMode: Active
    classifiers:
    - protectionId: httpbin
      hostname: '*'
      id: httpbin-sample
      path:
        operand: Prefix
        value: /
{{- end }}