{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: waas-logstash
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
spec:
  selector:
    configid: waas-logstash-container
  {{- include "waas.serviceTypeInternal" . }}
  ports:
    - port: {{ .Values.global.logstash.servicePort | default 2020 }}
      targetPort: {{ .Values.global.logstash.serviceTargetPort | default 2020 }}
      protocol: TCP
      name: {{ .Values.global.logstash.serviceAppProtocol | default "https" }}-lsinput
      {{ include "waas.nodeport" (dict "Values" .Values "Extra" "0") }}
{{- end }}
