apiVersion: v1
data:
  admin-user: {{ .Values.adminUser | b64enc | quote }}
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
kind: Secret
metadata:
  labels:
        configid: waas-grafana-secret
        {{- include "waas.labels" . | indent 8}}
  name: waas-grafana-user-secret
type: Opaque