{{- if and .Values.enabled .Values.global.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: waas-controller-role
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
rules:
  - apiGroups: ["waas.radware.com"]
    resources:
      - profiles
      - profiles/status
      - segments
      - segments/status
      - openapis
      - openapis/status
      - apispecs
      - apispecs/status
      - sourcegroups
      - sourcegroups/status
      - decodingbehaviors
      - decodingbehaviors/status
      - patterngroups
      - patterngroups/status
      - piiredactions
      - piiredactions/status
      - tokenvalidations
      - tokenvalidations/status
      - sigfilters
      - sigfilters/status
      - mappings
      - mappings/status
      - actors
      - actors/status
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
{{- end }}
