{{- if and .Values.enabled .Values.global.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: waas-controller-role-binding
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName | default "waas-controller-service-account" }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: waas-controller-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
