{{- if .Values.bypass }}
apiVersion: v1
kind: Service
metadata:
  name: sample-bypass-service
  labels:
    waas.radware.com/sample: bypass
spec:
  selector:
    app: sample-bypass-container
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
{{- end }}