{{- if and .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waas-prometheus-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
{{- end }}