apiVersion: v1
kind: ConfigMap
metadata:
  name: waas-grafana-datasources-config
  labels:
    {{- include "waas.labels" . | indent 4 }}
data:
  prometheus-datasource.yaml: |-
{{ .Files.Get "files/prometheus-datasource.yaml" | indent 4 }}
