{{- if and .Values.enabled .Values.credentialSecrets (default .Values.global.elasticsearch.enabled true) }}
apiVersion: v1
kind: Secret
metadata:
  name: waas-esauth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
data:
  user: {{ .Values.global.elasticsearchUser | b64enc | quote }}
  password: {{ .Values.global.elasticsearchPassword | b64enc | quote }}
{{- end }}
