{{- if and .Values.enabled .Values.global.certManager.enabled }}
{{- if or .Values.tls.clients.fluentbit.enabled .Values.tls.clients.controller.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: enforcer-client
spec:
  # Secret names are always required.
  secretName: waas-enforcer-client-secret

  # secretTemplate is optional. If set, these annotations and labels will be
  # copied to the Secret named example-com-tls. These labels and annotations will
  # be re-reconciled if the Certificate's secretTemplate changes. secretTemplate
  # is also enforced, so relevant label and annotation changes on the Secret by a
  # third party will be overwriten by cert-manager to match the secretTemplate.
  secretTemplate:
    labels:
      {{- include "waas.labels" . | indent 6 }}
    annotations:
      {{- include "waas.annotations" . | indent 6 }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - kwaf-demo.test
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: waas-enforcer-client
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - waas-enforcer-client.{{ .Release.Namespace }}.svc
    - waas-enforcer-client.{{ .Release.Namespace }}.svc.cluster.local
  # Issuer references are always required.
  issuerRef:
    name: {{ .Values.global.certManager.issuer }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
{{- end }}
