{{- if and .Values.enabled .Values.credentialSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: waas-gui-users-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
data:
  user: {{ .Values.global.guiUser | b64enc | quote }}
  password: {{ .Values.global.guiPassword | b64enc | quote }}
{{- end }}
