{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: waas-gui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
spec:
  selector:
    configid: waas-gui-container
  {{- include "waas.serviceTypeExposed" . }}
  ports:
    - port: {{ .Values.global.gui.servicePort | default 443 }}
      targetPort: {{ .Values.global.gui.serviceTargetPort | default 8080 }}
      {{ include "waas.nodeport" . }}
      protocol: TCP
      name: {{ .Values.global.gui.serviceAppProtocol | default "https" }}-gui
{{- end }}
