{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: waas-licenses-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
data:
  #This data section should include a list of kwaf licenses.
  #Every license string should be a key int this list with emty value.
  #Example:
  #RADWARE-kwaf-pods-20-21jun2020-21jul2020-tJWYAw2g: ""
{{- end }}