{{- if and .Values.global.openshift.enabled (default .Values.global.elasticsearch.enabled true) }}
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
# TODO - required for init container
allowPrivilegedContainer: true
# TODO -required for memory locking
allowedCapabilities:
- IPC_LOCK
- SYS_RESOURCE
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups: []
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: elastic allows using capabilities required by elastic
      (ipc_lock and sys_resource)
  name: {{ .Release.Namespace }}-elastic
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ .Release.Namespace }}:{{ .Values.serviceAccountName | default "waas-elasticsearch-service-account" }}
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
{{- end }}