{{- if and .Values.enabled .Values.global.rbac (default .Values.global.elasticsearch.enabled true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName | default "waas-elasticsearch-service-account" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
{{- end }}