{{- if .Values.perfNginx}}
apiVersion: v1
kind: Service
metadata:
  name: perf-nginx-service
  labels:
    waas.radware.com/sample: perf-nginx
spec:
  selector:
    app: perf-nginx-container
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
    - port: 8080
      name: ngmon
      protocol: TCP
      targetPort: 9113
{{- end }}