{{- if .Values.perfNginx}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: perf-nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes  auto;
    #error_log  /var/log/nginx/error.log;
    error_log  /dev/null;
    events {
      worker_connections  10240;
    }
    http {
      server {
              listen       80;
              server_name  localhost;
              access_log /dev/null;
              location / {
                  root   /usr/share/nginx/html;
                  index  index.html index.htm;
                  error_page 405 =200 $uri;
              }

              location /nginx_status {
                stub_status;
                #allow 127.0.0.1; allow requests from localhost
                #deny all; #deny other hosts
              }

              error_page   500 502 503 504  /50x.html;
              location = /50x.html {
                root   /usr/share/nginx/html;
              }
            }
          }
{{- end }}

