apiVersion: waas.radware.com/v1beta1
kind: APISpec
metadata:
  name: waas-api-profile-all-hs-3498933902
  namespace: test
spec:
  openAPINamespace: test
  openapi: ausf-auth-perf-6159957044
  patch: |
    [{
            "op": "add",
            "path": "/paths/~1ue-authentications/get",
            "value": {
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }, {
            "op": "add",
            "path": "/paths/~1index.html",
            "value": {
                "get": {
                    "responses": {
                        "200": {
                            "description": "OK"
                        }
                    },
                    "requestBody": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            },
                            "application/x-www-form-urlencoded": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "pattern": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "post": {
                    "responses": {
                        "200": {
                            "description": "OK"
                        }
                    },
                    "requestBody": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            },
                            "application/xml": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "pattern": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "string"
                                        }
                                    }
                                }
                            },
                            "text/html": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "text/js": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "application/x-www-form-urlencoded": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "pattern": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    ]
