apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    orgId: 1
    url: http://waas-prometheus-service:9090
    password:
    user:
    database:
    basicAuth: false
    isDefault: true
    version: 1
    editable: true