{
 "title": "WAAS EXT-AUTHZ Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(istio_requests_total,job)"
    }
   },
   { "name": "ns", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "app_svc",
    "label": "app service",
    "query": {
     "query": "label_values(istio_requests_total,destination_service)"
    }
   },
   {
    "name": "pf",
    "label": "profile",
    "query": {
     "query": "label_values(envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix!~\"ads_cluster|waas_metrics|admin\"},envoy_http_conn_manager_prefix)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ISTIO vs ENFORCER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "ISTIO - Latency  for response code  406",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.1, sum(rate(istio_request_duration_milliseconds_bucket{response_code=\"406\",destination_service=\"perf-nginx-service.test.svc.cluster.local\",job=\"$job\"}[1m])) by (le))",
       "legendFormat": "10%"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(istio_request_duration_milliseconds_bucket{response_code=\"406\",destination_service=\"perf-nginx-service.test.svc.cluster.local\",job=\"$job\"}[1m])) by (le))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{response_code=\"406\",destination_service=\"perf-nginx-service.test.svc.cluster.local\",job=\"$job\"}[1m])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{response_code=\"406\",destination_service=\"perf-nginx-service.test.svc.cluster.local\",job=\"$job\"}[1m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{response_code=\"406\",destination_service=\"perf-nginx-service.test.svc.cluster.local\",job=\"$job\"}[1m])) by (le))",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "ISTIO - Counter per Response Code",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(istio_requests_total{response_code=\"403\",destination_service=\"perf-nginx-service.test.svc.cluster.local\"}[1m])",
       "legendFormat": "{{response_code}}"
      },
      {
       "expr": "rate(istio_requests_total{response_code=\"406\",destination_service=\"perf-nginx-service.test.svc.cluster.local\"}[1m])",
       "legendFormat": "{{response_code}}"
      },
      {
       "expr": "rate(istio_requests_total{response_code=\"200\",destination_service=\"perf-nginx-service.test.svc.cluster.local\"}[1m])",
       "legendFormat": "{{response_code}}"
      }
     ]
    },
    {
     "title": "Request CX Active",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "envoy_listener_downstream_cx_active{envoy_listener_address=\"0.0.0.0_9000\", job=\"$job\"}",
       "legendFormat": "enforcer cx active"
      },
      {
       "expr": "envoy_listener_downstream_cx_active{listener_address=\"0.0.0.0_8080\",job=\"$job\"}",
       "legendFormat": "istio cx active"
      }
     ]
    }
   ]
  },
  { "title": "KWAF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Latency  Istio total",
   "type": "graph",
   "description": "Latency  Istio total",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum(irate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "5%"
    },
    {
     "expr": "histogram_quantile(0.10, sum(irate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "10%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\", job=\"$job\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\", job=\"$job\"}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\", job=\"$job\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{response_code=\"406\",destination_service=\"$app_svc\", job=\"$job\"}[1m])) by (le))",
     "legendFormat": "406"
    }
   ]
  },
  {
   "title": "Latency Istio bars",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "5%"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "10%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "70%"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "80%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=\"$app_svc\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Istio RQ and CX",
   "type": "stat",
   "description": "Istio req rate over 1minute",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(istio_requests_total{destination_service=\"$app_svc\",job=\"$job\",response_code=\"200\"}[1m])",
     "legendFormat": "RQ rate"
    },
    {
     "expr": "envoy_listener_downstream_cx_active{listener_address=\"0.0.0.0_8080\",job=\"$job\"}",
     "legendFormat": "CX active"
    },
    {
     "expr": "rate(envoy_listener_downstream_cx_total{listener_address=\"0.0.0.0_8080\",job=\"$job\"}[1m])",
     "legendFormat": "CX rate"
    }
   ]
  },
  {
   "title": "Rate over 1minute - Istio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_service=\"$app_svc\",job=\"$job\"}[1m]))by (response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Latency Istio  - Enforcer ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "5%"
    },
    {
     "expr": "histogram_quantile(0.10, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "10%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Latency Istio-Enforcer  bars",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "5%"
    },
    {
     "expr": "histogram_quantile(0.10, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "10%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.70, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "70%"
    },
    {
     "expr": "histogram_quantile(0.80, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "80%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(envoy_cluster_local_upstream_rq_time_bucket{cluster_name=\"outbound|9000||enforcer\",job=\"$job\"}[1m])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Enforcer RQ and CX",
   "type": "stat",
   "description": "Enforcer RQ and CX",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total {envoy_http_conn_manager_prefix=\"$pf\",job=\"$job\"}[1m]))",
     "legendFormat": "RQ rate"
    },
    {
     "expr": "envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=\"$pf\",job=\"$job\"}",
     "legendFormat": "CX  active "
    },
    {
     "expr": "sum(irate(envoy_http_downstream_cx_total {envoy_http_conn_manager_prefix=\"$pf\",job=\"$job\"}[1m]))",
     "legendFormat": "CX rate"
    }
   ]
  },
  {
   "title": "Rate over 1minute - Enforcer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total {envoy_http_conn_manager_prefix=\"$pf\",job=\"$job\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Latency  Enforcer",
   "type": "timeseries",
   "description": "Latency  Enforcer",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.05,sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\", job=\"$job\"}[1m])) by (le))",
     "legendFormat": "5%"
    },
    {
     "expr": "histogram_quantile(0.10,sum (rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\", job=\"$job\"}[1m])) by (le))",
     "legendFormat": "10%"
    },
    {
     "expr": "histogram_quantile(0.50,sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\", job=\"$job\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\", job=\"$job\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\", job=\"$job\"}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"lst-kwaf/waas-api-profile\", job=\"$job\"}[1m])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Latency Enforcer bars",
   "type": "bargauge",
   "description": "Latency Enforcer bars",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\"}[1m])) by (le))",
     "legendFormat": "5%"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\"}[1m])) by (le))",
     "legendFormat": "10%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\"}[1m])) by (le))",
     "legendFormat": "70%"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\"}[1m])) by (le))",
     "legendFormat": "80%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\"}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"$pf\"}[1m])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^.*$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Aggregated  PODs CPU over 1 minute",
   "type": "stat",
   "description": "Aggregated  PODs CPU over 1 minute",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"$ns\",pod=~\"istio-ingressgateway-.*\",container=~\"\"}[1m])))*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Istio's Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated{instance=~\".*.15090\"})",
     "legendFormat": "Allocated memory"
    },
    {
     "expr": "SUM(envoy_server_memory_heap_size{instance=~\".*.15090\"})",
     "legendFormat": "Heap Size"
    }
   ]
  },
  {
   "title": "Enforcer CPU",
   "type": "stat",
   "description": "Enforcer CPU",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{container=\"enforcer\" ,pod=~\"istio-ingressgateway-.*\",namespace=\"$ns\"}[1m])))*1000",
     "legendFormat": "counter"
    }
   ]
  },
  {
   "title": "Istio CPU",
   "type": "stat",
   "description": "Istio CPU",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": " (sum(rate(container_cpu_usage_seconds_total{namespace=\"$ns\",container=\"istio-proxy\",pod=~\"istio-ingressgateway-.*\"}[1m])))*1000",
     "legendFormat": "counter"
    }
   ]
  },
  {
   "title": "Total Enforcers Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated{instance=~\".*.19010\"})",
     "legendFormat": "Allocated memory"
    },
    {
     "expr": "SUM(envoy_server_memory_heap_size{instance=~\".*.19010\"})",
     "legendFormat": "Heap Size"
    }
   ]
  },
  {
   "title": "Number of Enforcers",
   "type": "graph",
   "description": "Number of Enforcers",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_server_live{instance=~\".*.15090\",job=\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Enforcer Status Code Classes",
   "type": "grafana-piechart-panel",
   "description": "Enforcer Status Code Classes",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"$pf\"}[5m])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\"^$node$\"})",
     "legendFormat": "Total  Cores"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cpu=\"total\",id=\"/\",instance=~\"^$node$\"}[1m]))",
     "legendFormat": "Used Cores"
    }
   ]
  },
  {
   "title": "Number of Enforcers",
   "type": "stat",
   "description": "Number of Enforcers",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{instance=~\".*.15090\",job=\"$job\"})",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "Ext AUTHZ rate over 1 minute",
   "type": "stat",
   "description": "Ext authz timeout rate over 1 minute",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ext_authz_ok{cluster_name=\"outbound|80||perf-nginx-service.test.svc.cluster.local\", job=\"$job\"}[1m]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(envoy_cluster_ext_authz_denied{cluster_name=\"outbound|80||perf-nginx-service.test.svc.cluster.local\", job=\"$job\"}[1m]))",
     "legendFormat": "Denied"
    },
    {
     "expr": "sum(rate(envoy_cluster_ext_authz_error{cluster_name=\"outbound|80||perf-nginx-service.test.svc.cluster.local\", job=\"$job\"}[1m]))",
     "legendFormat": "Error"
    }
   ]
  }
 ]
}