{
 "title": "WAAS Dashboard",
 "description": "WAAS dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{envoy_cluster_name!~\"ads_cluster|rl_cluster|waas_metrics\"},envoy_cluster_name)"
    }
   },
   {
    "name": "downstream",
    "label": "Downstream http-conn-mngr prefix",
    "query": {
     "query": "label_values(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix!~\"admin|waas_metrics|lst-healthcheck\"},envoy_http_conn_manager_prefix)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total vs. Blocked HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_total_requests{envoy_http_conn_manager_prefix=\"$downstream\"}[1m])) - sum(rate(envoy_http_enforcer_downstream_rq{envoy_http_conn_manager_prefix=\"$downstream\",type=\"blocked\"}[1m]))",
     "legendFormat": "Valid"
    },
    {
     "expr": "sum(rate(envoy_http_enforcer_downstream_rq{envoy_http_conn_manager_prefix=\"$downstream\",type=\"blocked\"}[1m]))",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Legitimate vs. Blocked",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_enforcer_downstream_rq{envoy_http_conn_manager_prefix=\"$downstream\",type=\"legitimate\"}[1m]))",
     "legendFormat": "Legitimate"
    },
    {
     "expr": "sum(rate(envoy_http_enforcer_downstream_rq{envoy_http_conn_manager_prefix=\"$downstream\",type=\"blocked\"}[1m]))",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Downstream Connections per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"$downstream\"}[1m]))",
     "legendFormat": "Connections/second"
    }
   ]
  },
  {
   "title": "Upstream Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"$cluster\"}[1m])",
     "legendFormat": "Requests/second"
    }
   ]
  },
  {
   "title": "Protected Entity Status Codes",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$cluster\"}[1m])) by (envoy_response_code)",
     "legendFormat": "{{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Protected Entity Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$cluster\"}[1m])) by (envoy_response_code)",
     "legendFormat": "{{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Average Heap Size over time (global)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "AVG(envoy_server_memory_heap_size)",
     "legendFormat": "Heap Size"
    }
   ]
  },
  {
   "title": "Average Heap Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "AVG(envoy_server_memory_heap_size)"
    }
   ]
  },
  {
   "title": "Enforcer Status Code Classes",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"$downstream\"}[1m])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Enforcer Status Code Classes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"$downstream\"}[1m])) by (envoy_response_code_class)",
     "legendFormat": "{{ envoy_response_code_class }}xx"
    }
   ]
  },
  {
   "title": "Network Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (rate(envoy_http_downstream_cx_rx_bytes_total {envoy_http_conn_manager_prefix=~\"$downstream\"}[1m])) by (service)",
     "legendFormat": "inbound"
    },
    {
     "expr": "sum (rate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=~\"$downstream\"}[1m])) by (service)",
     "legendFormat": "outbound"
    }
   ]
  }
 ]
}