{{- if .Values.nginxh2c}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nginxh2c-deployment
  labels:
    waas.radware.com/sample: nginxh2c
spec:
  selector:
    matchLabels:
      app: sample-nginxh2c-container
  template:
    metadata:
      labels:
        app: sample-nginxh2c-container
        waas.radware.com/protection: enabled
    spec:
      containers:
        - args:
          - "-c"
          - "sed -i 's@listen       8080;@listen       8080 http2; listen       [::]:8080 http2; error_page 405 =200 $uri;@' /etc/nginx/conf.d/default.conf && /docker-entrypoint.sh nginx -g 'daemon off;'"
          command: ["/bin/sh"]
          image: nginxinc/nginx-unprivileged:stable-alpine
          imagePullPolicy: IfNotPresent
          name: sample-nginx
{{- end }}