{{- if and .Values.enabled .Values.global.elasticsearch.setElasticTimestamp }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: waas-elasticsearch-pipelines
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
data:
  final-pipeline.json: |-
  {{- tpl (.Files.Get "files/waas-final-pipeline.json") $  | nindent 4 }}
{{- end }}