{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: waas-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
spec:
  selector:
    configid: waas-controller-container
  {{- include "waas.serviceTypeInternal" . }}
  ports:
    - port: {{ .Values.global.controller.servicePort | default 12121 }}
      targetPort: {{ .Values.global.controller.serviceTargetPort | default 12121 }}
      name: {{ .Values.global.controller.serviceAppProtocol | default "tcp" }}-xds
      protocol: TCP
      {{ include "waas.nodeport" . }}
{{- end }}
