{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: waas-identity-auth-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
data:
  AUTH_ACCESS_EXPIRATION: {{ .Values.global.guiAuthAccessExpirationTime | quote }}
  AUTH_METHOD:  {{ .Values.global.guiAuthMethod | quote }}
{{- end }}
