{{- if and .Values.enabled (default .Values.global.elasticsearch.enabled true) }}
{{- if eq .Values.persistentStorage.type "google" }}
{{- /* storgae class to use when installing in GKE */}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: waas-elasticsearch-google-disk
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: {{ .Values.volumeBindingMode }}
{{- end }}
{{- end }}