{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: waas-validation-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
spec:
  selector:
    configid: waas-validation-controller-container
  {{- include "waas.serviceTypeInternal" . }}
  ports:
    - port: {{ .Values.global.validationController.servicePort | default 443 }}
      targetPort: {{ .Values.global.validationController.serviceTargetPort | default 4443 }}
      name:  {{ .Values.global.validationController.serviceAppProtocol | default "https" }}-waasvc
      protocol: TCP
      {{ include "waas.nodeport" . }}
{{- end }}
