{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: waas-rate-limiter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waas.labels" . | indent 4 }}
  annotations:
    {{- include "waas.annotations" . | indent 4 }}
spec:
  selector:
    configid: waas-rate-limiter-container
{{- if .Values.isHeadless }}
  type: ClusterIP
  clusterIP: None
{{- else }}
{{- if .Values.useNodePort }}
  type: NodePort
{{- else }}
  {{- include "waas.serviceTypeInternal" . }}
{{- end }}
{{- end }}
  ports:
    - port: {{ .Values.global.ratelimiter.servicePort | default 8081}}
      targetPort: {{ .Values.global.ratelimiter.serviceTargetPort | default 8081}}
      name: {{ .Values.global.ratelimiter.serviceAppProtocol | default "tcp"}}-rl
      protocol: TCP
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: {{ .Values.global.ratelimiter.metricServiceAppProtocol | default "http"}}-metrics
{{- end }}
